name: Compile tex

on:
  workflow_dispatch:
    inputs:
      directory-sorgente:
        description: "Directory file sorgente"
        required: true
      directory-destinazione:
        description: "Directory destinazione pdf"
        required: true
      nome-pdf:
        description: "Nome del pdf da creare"
        required: true
      elimina-sorgenti:
        description: "Elimina i file sorgenti"
        type: boolean
        required: true
        default: false

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Ensure Python is set up (if needed)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Run LaTeX compilation
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: ${{ inputs.directory-sorgente }}
          latexmk_use_lualatex: true

      # Move the generated PDF to the destination directory
      - name: Move compiled PDF
        run: |
          mv ${{ inputs.directory-sorgente }}/main.pdf ${{ inputs.directory-destinazione }}/${{ inputs.nome-pdf }}.pdf

      # Optionally delete the source files after compilation
      - name: Commit and push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          if [ ${{ inputs.elimina-sorgenti }} == true ]; then
            rm -r ${{ inputs.directory-sorgente }}
            git add -A
          else
            git add '*.pdf' '*.tex'
          fi

          git commit -m "Compiled LaTeX document and moved PDF"

          # Pull the latest changes from master
          git pull --rebase https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} master

          # Push changes to master
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:master
