name: Compile and Move PDF

on:
  workflow_dispatch:
    inputs:
      directory-sorgente:
        description: "Directory file sorgente"
        required: true
      directory-destinazione:
        description: "Directory destinazione pdf"
        required: true
      nome-pdf:
        description: "Nome del pdf da creare"
        required: true

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      # Checkout the develop branch
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop # Ensure we are in the develop branch

      # Ensure Python is set up (if needed)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Run LaTeX compilation
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: ${{ inputs.directory-sorgente }}
          latexmk_use_lualatex: true

      # Move the compiled PDF to the destination directory
      - name: Create destination directory
        run: |
          mkdir -p ${{ inputs.directory-destinazione }}

      # Move the compiled PDF to the destination directory with the new name
      - name: Move compiled PDF to sources
        run: |
          if [ -f ${{ inputs.directory-sorgente }}/main.pdf ]; then
            mv ${{ inputs.directory-sorgente }}/main.pdf ${{ inputs.directory-sorgente }}/${{ inputs.nome-pdf }}.pdf
          else
            echo "Error: main.pdf not found in the source directory"
            exit 1
          fi

      # Checkout master branch
      - name: Checkout master branch
        run: |
          git fetch origin master
          git checkout master

      # Create destination directory in master if it doesn't exist
      - name: Create destination directory in master
        run: |
          mkdir -p ${{ inputs.directory-destinazione }}

      # Copy PDF from sources branch to master branch destination
      - name: Copy PDF to master branch
        run: |
          cp ${{ inputs.directory-sorgente }}/${{ inputs.nome-pdf }}.pdf ${{ inputs.directory-destinazione }}/${{ inputs.nome-pdf }}.pdf
          git add ${{ inputs.directory-destinazione }}/${{ inputs.nome-pdf }}.pdf

      # Commit and push the PDF to the master branch
      - name: Commit and push PDF to master
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git commit -m "Added compiled PDF to master"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:master
